# Generated by Django 3.2.16 on 2023-02-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=15)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PIN code',
                'verbose_name_plural': 'PIN code',
            },
        ),
    ]
