# Generated by Django 3.2.16 on 2022-12-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=25)),
                ('fullname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('is_return', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
            },
        ),
    ]
