# Generated by Django 3.2.16 on 2023-02-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsKeyTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=100)),
                ('code_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
            ],
        ),
    ]
