# Generated by Django 3.2.16 on 2023-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingskeytaking',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
