# Generated by Django 3.2.16 on 2023-02-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_options'),
        ('keytaking', '0002_settingskeytaking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingskeytaking',
            options={'verbose_name': 'Settings KeyTaking', 'verbose_name_plural': 'Settings KeyTaking'},
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='settingskeytaking',
            name='room',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
