# Generated by Django 3.2.16 on 2022-12-19 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaking', '0002_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.datetime.now, max_length=10),
        ),
    ]
