# Generated by Django 3.2.16 on 2022-12-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaking', '0003_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(auto_now_add=True, max_length=10),
        ),
    ]
