# Generated by Django 3.2.16 on 2023-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='map_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
