# Generated by Django 3.2.9 on 2023-03-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('keytaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='role',
            field=models.ManyToManyField(to='user.Role'),
        ),
    ]
