# Generated by Django 3.2.16 on 2023-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0002_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingskeytaking',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
    ]
