# Generated by Django 3.2.16 on 2023-04-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mainuser_role'),
        ('keytaker', '0002_alter_room_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_study_room',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudyRoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('lesson', 'Lesson'), ('free', 'Free'), ('reserved', 'Reserved'), ('busy', 'Busy')], default='inactive', max_length=20)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mainuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keytaker.room')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mainuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keytaker.room')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
