# Generated by Django 3.2.16 on 2023-02-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0002_alter_room_map_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
