# Generated by Django 3.2.16 on 2023-02-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0003_settingskeytaking_in_process'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettingsKeyTaking',
            new_name='SettingsKeyTaker',
        ),
        migrations.AlterModelOptions(
            name='settingskeytaker',
            options={'verbose_name': 'Settings KeyTaker', 'verbose_name_plural': 'Settings KeyTaker'},
        ),
    ]
