# Generated by Django 3.2.16 on 2023-04-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mainuser_role'),
        ('keytaker', '0004_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroomschedule',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.mainuser'),
        ),
    ]
