# Generated by Django 3.2.16 on 2023-02-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0004_auto_20230210_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='category',
            new_name='role',
        ),
    ]
