# Generated by Django 3.2.16 on 2023-04-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0005_alter_studyroomschedule_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedule'},
        ),
        migrations.AlterModelOptions(
            name='studyroomschedule',
            options={'verbose_name': 'StudyRoom Schedule', 'verbose_name_plural': 'StudyRoom Schedule'},
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('key', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField()),
                ('is_take', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keytaker.room')),
            ],
        ),
    ]
