# Generated by Django 3.2.16 on 2023-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0006_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
