# Generated by Django 3.2.16 on 2023-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0007_auto_20230210_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
