# Generated by Django 3.2.16 on 2023-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0008_alter_orders_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
