# Generated by Django 3.2.16 on 2023-05-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0008_reservationhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationHistory',
        ),
    ]
