# Generated by Django 3.2.16 on 2023-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keytaker', '0009_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='map_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
